version: '2'
services:
  webserver:
    build:
      context: ./conf/
    image: laravel
    ports:
      - "80:80"
      - "8080:80"
    restart: always
    volumes:
      - ../www:/var/www
    tty: true
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=senharoot
    volumes:
      - ./mysql-data:/var/lib/mysql
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    links:
      - mysql:db
    ports:
      - "8090:80"
    depends_on:
      - mysql
